{% set version = "6.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ipmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ipmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ipmisc/ipmisc_{{ version }}.tar.gz
  sha256: d3b3589fcb9eb977510da1d3fea58781f11f48312abbb26f386387296e09c8b6

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crayon
    - r-dplyr
    - r-forcats
    - r-magrittr
    - r-rlang
    - r-rstudioapi
    - r-tibble
    - r-tidyr
    - r-zeallot
  run:
    - r-base
    - r-crayon
    - r-dplyr
    - r-forcats
    - r-rlang
    - r-rstudioapi
    - r-tibble
    - r-tidyr
    - r-zeallot

test:
  commands:
    - $R -e "library('ipmisc')"           # [not win]
    - "\"%R%\" -e \"library('ipmisc')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/ipmisc/, https://github.com/IndrajeetPatil/ipmisc
  license: GPL-3.0-only
  summary: "Provides functions needed for data cleaning and formatting and forms data cleaning and wrangling backend for the following packages: 'ggstatsplot', 'groupedstats', 'pairwiseComparisons', and 'statsExpressions'."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: ipmisc
# Title: Miscellaneous Functions for Data Cleaning and Analysis
# Version: 1.1.0
# Authors@R: person(given = "Indrajeet", family = "Patil", role = c("aut", "cre"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Provides functions needed for data cleaning and formatting and forms data cleaning and wrangling backend for the following packages: 'ggstatsplot', 'groupedstats', 'pairwiseComparisons', and 'statsExpressions'.
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/ipmisc/, https://github.com/IndrajeetPatil/ipmisc
# BugReports: https://github.com/IndrajeetPatil/ipmisc/issues
# Depends: R (>= 3.5.0)
# Imports: broomExtra, crayon, dplyr (>= 0.8.3), forcats, rlang (>= 0.4.2), rstudioapi, tibble (>= 2.0.1), tidyr (>= 1.0.0), zeallot
# Suggests: ggplot2, knitr, parameters, rmarkdown, spelling, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.0.2.9000
# NeedsCompilation: no
# Packaged: 2020-02-09 12:01:51 UTC; inp099
# Author: Indrajeet Patil [aut, cre] (<https://orcid.org/0000-0003-1995-6531>)
# Repository: CRAN
# Date/Publication: 2020-02-09 12:50:02 UTC
